cmake_minimum_required(VERSION 3.16)
project(controller_feedback)
find_package(ament_cmake REQUIRED)
find_package(navigo_core REQUIRED)
find_package(navigo_costmap_2d REQUIRED)
find_package(pluginlib REQUIRED)
find_package(tf2_ros REQUIRED)
find_package(yaml-cpp REQUIRED)
find_package(xtensor REQUIRED)
add_executable(controller_feedback controller_feedback.cpp)
target_compile_features(controller_feedback PRIVATE cxx_std_17)
ament_target_dependencies(controller_feedback navigo_core navigo_costmap_2d pluginlib tf2_ros)
target_link_libraries(controller_feedback yaml-cpp xtensor)
